// GENERATED by scripts/generate.mjs — do not hand-edit. See the README's
// "Adding a new component" section.
// Global ambient module: importing this file anywhere (even `import '@dynamia-tools/tailadmin-vue-wc/elements'`
// for its side effect only) makes every `ta-*` tag fully typed in `document.createElement`,
// `querySelector`, and this package's `mount()` helper.
import type { Writable } from './helpers'
import type { AlertProps } from './components/ta-alert'
import type { AvatarProps } from './components/ta-avatar'
import type { BadgeProps } from './components/ta-badge'
import type { ButtonProps } from './components/ta-button'
import type { ModalProps } from './components/ta-modal'
import type { YoutubeEmbedProps } from './components/ta-youtube-embed'
import type { ResponsiveImageProps } from './components/ta-responsive-image'
import type { TwoColumnImageGridProps } from './components/ta-two-column-image-grid'
import type { ThreeColumnImageGridProps } from './components/ta-three-column-image-grid'
import type { ComponentCardProps } from './components/ta-component-card'
import type { CountdownProps } from './components/ta-countdown'
import type { DropdownMenuProps } from './components/ta-dropdown-menu'
import type { PageBreadcrumbProps } from './components/ta-page-breadcrumb'
import type { CommonGridShapeProps } from './components/ta-common-grid-shape'
import type { CheckboxInputProps } from './components/ta-checkbox-input'
import type { DefaultInputsProps } from './components/ta-default-inputs'
import type { DropzoneProps } from './components/ta-dropzone'
import type { FileInputProps } from './components/ta-file-input'
import type { InputGroupProps } from './components/ta-input-group'
import type { InputStateProps } from './components/ta-input-state'
import type { MultipleSelectProps } from './components/ta-multiple-select'
import type { RadioInputsProps } from './components/ta-radio-inputs'
import type { SelectInputProps } from './components/ta-select-input'
import type { TextAreaProps } from './components/ta-text-area'
import type { ToggleSwitchProps } from './components/ta-toggle-switch'
import type { EmptyStateProps } from './components/ta-empty-state'
import type { MarkdownViewerProps } from './components/ta-markdown-viewer'
import type { CtaProps } from './components/ta-cta'
import type { FaqAccordionProps } from './components/ta-faq-accordion'
import type { FeatureGridProps } from './components/ta-feature-grid'
import type { FooterProps } from './components/ta-footer'
import type { HeroProps } from './components/ta-hero'
import type { LandingProps } from './components/ta-landing'
import type { LoginDialogProps } from './components/ta-login-dialog'
import type { PricingTableProps } from './components/ta-pricing-table'
import type { TabsProps } from './components/ta-tabs'
import type { TestimonialProps } from './components/ta-testimonial'
import type { AuthSplitProps } from './components/ta-auth-split'
import type { BorderLayoutProps } from './components/ta-border-layout'
import type { DocsLayoutProps } from './components/ta-docs-layout'
import type { MobileAppLayoutProps } from './components/ta-mobile-app-layout'
import type { NavbarProps } from './components/ta-navbar'
import type { ColorPickerProps } from './components/ta-color-picker'
import type { MoneyInputProps } from './components/ta-money-input'
import type { NumericKeypadProps } from './components/ta-numeric-keypad'
import type { PaymentInputProps } from './components/ta-payment-input'
import type { PinInputProps } from './components/ta-pin-input'
import type { QuantityInputProps } from './components/ta-quantity-input'
import type { RatingProps } from './components/ta-rating'
import type { ScannerInputProps } from './components/ta-scanner-input'
import type { MapProps } from './components/ta-map'
import type { PdfViewerProps } from './components/ta-pdf-viewer'
import type { QrCodeProps } from './components/ta-qr-code'
import type { StatusProps } from './components/ta-status'
import type { SummaryProps } from './components/ta-summary'
import type { TimelineProps } from './components/ta-timeline'
import type { DropFileUploaderProps } from './components/ta-drop-file-uploader'
import type { ImageCropperProps } from './components/ta-image-cropper'
import type { SignaturePadProps } from './components/ta-signature-pad'
import type { SoundPlayerProps } from './components/ta-sound-player'
import type { WebcamProps } from './components/ta-webcam'
import type { CommandPaletteProps } from './components/ta-command-palette'
import type { FabProps } from './components/ta-fab'
import type { KanbanProps } from './components/ta-kanban'
import type { MenuProps } from './components/ta-menu'
import type { CalendarProps } from './components/ta-calendar'
import type { DateRangePickerProps } from './components/ta-date-range-picker'
import type { TimeSlotPickerProps } from './components/ta-time-slot-picker'
import type { CartProps } from './components/ta-cart'
import type { ItemCardProps } from './components/ta-item-card'
import type { ItemGridProps } from './components/ta-item-grid'
import type { PrintPreviewProps } from './components/ta-print-preview'
import type { SelectionGridProps } from './components/ta-selection-grid'
import type { DataGridProps } from './components/ta-data-grid'
import type { DataTableProps } from './components/ta-data-table'
import type { EntityAutocompleteProps } from './components/ta-entity-autocomplete'
import type { EntitySelectorProps } from './components/ta-entity-selector'
import type { ItemSelectorProps } from './components/ta-item-selector'
import type { TreeTableProps } from './components/ta-tree-table'
import type { LazyLoaderProps } from './components/ta-lazy-loader'
import type { BarChartOneProps } from './components/ta-bar-chart-one'
import type { LineChartOneProps } from './components/ta-line-chart-one'
import type { EcommerceMetricsProps } from './components/ta-ecommerce-metrics'
import type { MonthlyTargetProps } from './components/ta-monthly-target'
import type { MonthlySaleProps } from './components/ta-monthly-sale'
import type { StatisticsChartProps } from './components/ta-statistics-chart'
import type { CustomerDemographicProps } from './components/ta-customer-demographic'
import type { RecentOrdersProps } from './components/ta-recent-orders'
import type { ProfileCardProps } from './components/ta-profile-card'
import type { PersonalInfoCardProps } from './components/ta-personal-info-card'
import type { AddressCardProps } from './components/ta-address-card'
import type { DangerZoneProps } from './components/ta-danger-zone'
import type { SecurityProps } from './components/ta-security'
import type { ProfileModalProps } from './components/ta-profile-modal'
import type { TableProps } from './components/ta-table'
import type { TableHeaderProps } from './components/ta-table-header'
import type { TableBodyProps } from './components/ta-table-body'
import type { TableRowProps } from './components/ta-table-row'
import type { TableCellProps } from './components/ta-table-cell'
import type { BasicTableOneProps } from './components/ta-basic-table-one'

declare global {
  interface HTMLElementTagNameMap {
    'ta-alert': HTMLElement & Writable<AlertProps>
    'ta-avatar': HTMLElement & Writable<AvatarProps>
    'ta-badge': HTMLElement & Writable<BadgeProps>
    'ta-button': HTMLElement & Writable<ButtonProps>
    'ta-modal': HTMLElement & Writable<ModalProps>
    'ta-youtube-embed': HTMLElement & Writable<YoutubeEmbedProps>
    'ta-responsive-image': HTMLElement & Writable<ResponsiveImageProps>
    'ta-two-column-image-grid': HTMLElement & Writable<TwoColumnImageGridProps>
    'ta-three-column-image-grid': HTMLElement & Writable<ThreeColumnImageGridProps>
    'ta-component-card': HTMLElement & Writable<ComponentCardProps>
    'ta-countdown': HTMLElement & Writable<CountdownProps>
    'ta-dropdown-menu': HTMLElement & Writable<DropdownMenuProps>
    'ta-page-breadcrumb': HTMLElement & Writable<PageBreadcrumbProps>
    'ta-common-grid-shape': HTMLElement & Writable<CommonGridShapeProps>
    'ta-checkbox-input': HTMLElement & Writable<CheckboxInputProps>
    'ta-default-inputs': HTMLElement & Writable<DefaultInputsProps>
    'ta-dropzone': HTMLElement & Writable<DropzoneProps>
    'ta-file-input': HTMLElement & Writable<FileInputProps>
    'ta-input-group': HTMLElement & Writable<InputGroupProps>
    'ta-input-state': HTMLElement & Writable<InputStateProps>
    'ta-multiple-select': HTMLElement & Writable<MultipleSelectProps>
    'ta-radio-inputs': HTMLElement & Writable<RadioInputsProps>
    'ta-select-input': HTMLElement & Writable<SelectInputProps>
    'ta-text-area': HTMLElement & Writable<TextAreaProps>
    'ta-toggle-switch': HTMLElement & Writable<ToggleSwitchProps>
    'ta-empty-state': HTMLElement & Writable<EmptyStateProps>
    'ta-markdown-viewer': HTMLElement & Writable<MarkdownViewerProps>
    'ta-cta': HTMLElement & Writable<CtaProps>
    'ta-faq-accordion': HTMLElement & Writable<FaqAccordionProps>
    'ta-feature-grid': HTMLElement & Writable<FeatureGridProps>
    'ta-footer': HTMLElement & Writable<FooterProps>
    'ta-hero': HTMLElement & Writable<HeroProps>
    'ta-landing': HTMLElement & Writable<LandingProps>
    'ta-login-dialog': HTMLElement & Writable<LoginDialogProps>
    'ta-pricing-table': HTMLElement & Writable<PricingTableProps>
    'ta-tabs': HTMLElement & Writable<TabsProps>
    'ta-testimonial': HTMLElement & Writable<TestimonialProps>
    'ta-auth-split': HTMLElement & Writable<AuthSplitProps>
    'ta-border-layout': HTMLElement & Writable<BorderLayoutProps>
    'ta-docs-layout': HTMLElement & Writable<DocsLayoutProps>
    'ta-mobile-app-layout': HTMLElement & Writable<MobileAppLayoutProps>
    'ta-navbar': HTMLElement & Writable<NavbarProps>
    'ta-color-picker': HTMLElement & Writable<ColorPickerProps>
    'ta-money-input': HTMLElement & Writable<MoneyInputProps>
    'ta-numeric-keypad': HTMLElement & Writable<NumericKeypadProps>
    'ta-payment-input': HTMLElement & Writable<PaymentInputProps>
    'ta-pin-input': HTMLElement & Writable<PinInputProps>
    'ta-quantity-input': HTMLElement & Writable<QuantityInputProps>
    'ta-rating': HTMLElement & Writable<RatingProps>
    'ta-scanner-input': HTMLElement & Writable<ScannerInputProps>
    'ta-map': HTMLElement & Writable<MapProps>
    'ta-pdf-viewer': HTMLElement & Writable<PdfViewerProps>
    'ta-qr-code': HTMLElement & Writable<QrCodeProps>
    'ta-status': HTMLElement & Writable<StatusProps>
    'ta-summary': HTMLElement & Writable<SummaryProps>
    'ta-timeline': HTMLElement & Writable<TimelineProps>
    'ta-drop-file-uploader': HTMLElement & Writable<DropFileUploaderProps>
    'ta-image-cropper': HTMLElement & Writable<ImageCropperProps>
    'ta-signature-pad': HTMLElement & Writable<SignaturePadProps>
    'ta-sound-player': HTMLElement & Writable<SoundPlayerProps>
    'ta-webcam': HTMLElement & Writable<WebcamProps>
    'ta-command-palette': HTMLElement & Writable<CommandPaletteProps>
    'ta-fab': HTMLElement & Writable<FabProps>
    'ta-kanban': HTMLElement & Writable<KanbanProps>
    'ta-menu': HTMLElement & Writable<MenuProps>
    'ta-calendar': HTMLElement & Writable<CalendarProps>
    'ta-date-range-picker': HTMLElement & Writable<DateRangePickerProps>
    'ta-time-slot-picker': HTMLElement & Writable<TimeSlotPickerProps>
    'ta-cart': HTMLElement & Writable<CartProps>
    'ta-item-card': HTMLElement & Writable<ItemCardProps>
    'ta-item-grid': HTMLElement & Writable<ItemGridProps>
    'ta-print-preview': HTMLElement & Writable<PrintPreviewProps>
    'ta-selection-grid': HTMLElement & Writable<SelectionGridProps>
    'ta-data-grid': HTMLElement & Writable<DataGridProps>
    'ta-data-table': HTMLElement & Writable<DataTableProps>
    'ta-entity-autocomplete': HTMLElement & Writable<EntityAutocompleteProps>
    'ta-entity-selector': HTMLElement & Writable<EntitySelectorProps>
    'ta-item-selector': HTMLElement & Writable<ItemSelectorProps>
    'ta-tree-table': HTMLElement & Writable<TreeTableProps>
    'ta-lazy-loader': HTMLElement & Writable<LazyLoaderProps>
    'ta-bar-chart-one': HTMLElement & Writable<BarChartOneProps>
    'ta-line-chart-one': HTMLElement & Writable<LineChartOneProps>
    'ta-ecommerce-metrics': HTMLElement & Writable<EcommerceMetricsProps>
    'ta-monthly-target': HTMLElement & Writable<MonthlyTargetProps>
    'ta-monthly-sale': HTMLElement & Writable<MonthlySaleProps>
    'ta-statistics-chart': HTMLElement & Writable<StatisticsChartProps>
    'ta-customer-demographic': HTMLElement & Writable<CustomerDemographicProps>
    'ta-recent-orders': HTMLElement & Writable<RecentOrdersProps>
    'ta-profile-card': HTMLElement & Writable<ProfileCardProps>
    'ta-personal-info-card': HTMLElement & Writable<PersonalInfoCardProps>
    'ta-address-card': HTMLElement & Writable<AddressCardProps>
    'ta-danger-zone': HTMLElement & Writable<DangerZoneProps>
    'ta-security': HTMLElement & Writable<SecurityProps>
    'ta-profile-modal': HTMLElement & Writable<ProfileModalProps>
    'ta-table': HTMLElement & Writable<TableProps>
    'ta-table-header': HTMLElement & Writable<TableHeaderProps>
    'ta-table-body': HTMLElement & Writable<TableBodyProps>
    'ta-table-row': HTMLElement & Writable<TableRowProps>
    'ta-table-cell': HTMLElement & Writable<TableCellProps>
    'ta-basic-table-one': HTMLElement & Writable<BasicTableOneProps>
  }
}

export {}
